### ISSUE TITLE
AssertionError: cannot handle sectiondef kind=var

### ISSUE THREAD

**Issue by ghost** [ceph/asphyxiate#1]
<pre>
asphyxiate.render:DEBUG: Rendering sectiondef doxygen/xml/tracing_2librados_8h.xml:66

Exception occurred:
  File "/home/loic/software/ceph/ceph/build-doc/virtualenv/src/asphyxiate/asphyxiate/__init__.py", line 300, in render_sectiondef
    "cannot handle {node.tag} kind={node.attrib[kind]}".format(node=node)
AssertionError: cannot handle sectiondef kind=var
</pre>

**Comment by ghost** [comment]
Alfredo Deza suggests something like https://github.com/ceph/ceph/commit/9ff914405ccfb69ee33dd91f8a4e814c6609b25a

**Comment by tchaikov** [comment]
@dachary guess we can close this ticket now =)

**Comment by ghost** [comment]
yeah !

**Comment by ghost** [comment]
I guess we could also close the project in a few months from now.

**Comment by dmick** [comment]
well....have we resolved the "sphinx/breathe eats your machine" issue?

**Comment by ghost** [comment]
@dmick yes, simply by white listing the few files that need to be run thru doxygen instead of having it (in)digest the whole source tree.

**Comment by tchaikov** [comment]
@dmick yes, i put the two referenced source files into the list of breathe (see conf.py) from where it collects rendered files at seeing doxygenfile directives in .rst file. so sphinx/breathe will only process these two files. in other words, we speed up the build-doc and build-doc will use less memory. on my debian, it uses 200MB mem top.
